### ISSUE TITLE
Little square only showing

### ISSUE THREAD

**Issue by vegastriguy** [senlin/so-mobile-map-widget#9]
I have used your plugin on many websites and it works great.   For some reason, on this new website I am using it on all it does is show a small broken square (maybe 25px by 25px) and no map.   This is an updated theme that I use on many websites where it works find there and with this new theme I do not have any funky plugins that I have not used on other sites.  I am baffled.  Would you have any ideas?

**Comment by vegastriguy** [comment]
![image](https://cloud.githubusercontent.com/assets/1490218/24915178/5375ecee-1e8b-11e7-9dfe-5ca87512486b.png)

**Comment by senlin** [comment]
Hi Robert,

That sounds like a very weird issue indeed.

Do you have a site URL where this happens and also a URL of a site where the theme is running and the plugin shows fine?

**Comment by senlin** [comment]
Almost always these type of things are either plugin or theme related.

On the URL you gave I see that you're using a child theme of the Impreza theme. Are all child themes the exact same? Are they all using the same version of the parent theme? Are there any plugins installed that are different?

This can be so many things, but the fact that you have it working on many other sites, coupled with the fact that your issue is unique (meaning it has not been reported by others), means that there is a very high probability it has nothing to do with the plugin.

I can take a very brief look if you want. You can send me your details using https://revealit.me/ and then paste the URL [on the contact form of one of my sites](https://bohanintl.com/hire-bhi/?topic=other)

**Comment by vegastriguy** [comment]
Hi Piet...
Ok, too bad but it is not worth your effort....I will just use Google Map
html.   I reverted to the standard wordpress theme and turned off all
plugins (I should have done that first) and still a problem.  Then, I
deleted the plugin, and ftp'ed and older version, updated it, and still the
problem.  So, something is wonky with this WP install but not worth doing a
fresh install....thanks for the your quick replies and sorry to bother you.

**Comment by senlin** [comment]
Hi Robert,
From the screenshot it seems the image is missing, which could mean it has something to do with the URL. This in turn can point to an invalid parameter. You can try to copy the parameters from a working site to this site in development.
HTH
